import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import TopNav from "@/components/TopNav";
import MobileNav from "@/components/MobileNav";
import { MobileMenuProvider } from "@/context/MobileMenuContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "University",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
      <MobileMenuProvider>
        <TopNav />
        <Navbar />
        <MobileNav />
        
        {children}
        </MobileMenuProvider>
      </body>
    </html>
  );
}
